namespace PetCare.Application.Features.Auth.TwoFactor.VerifyTotpSetup;

using MediatR;
using PetCare.Application.Dtos.AuthDtos;

/// <summary>
/// Represents a request to verify a time-based one-time password (TOTP) code during multi-factor authentication setup.
/// </summary>
/// <param name="Code">The TOTP code to be verified. This value is typically generated by an authenticator app and must match the expected
/// code for the current time window.</param>
public sealed record VerifyTotpSetupCommand(string Code)
    : IRequest<VerifyTotpSetupResponseDto>;
