namespace PetCare.Application.Features.Auth.TwoFactor.VerifyTotp;

using MediatR;
using PetCare.Application.Dtos.AuthDtos;

/// <summary>
/// Represents a request to verify a time-based one-time password (TOTP) code for two-factor authentication.
/// </summary>
/// <param name="TwoFaToken">The token that identifies the two-factor authentication session. Cannot be null or empty.</param>
/// <param name="Code">The TOTP code to be verified. Must be a valid code generated by the authenticator application.</param>
public sealed record VerifyTotpCommand(
    string TwoFaToken,
    string Code)
    : IRequest<VerifyTotpResponseDto>;
